using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Subro.RecordForge;
using System.Text;

namespace Subro.Generators
{
    /// <summary>
    /// Completes a partial type against the interfaces named in <see cref="ImplementsAttribute"/>, adding a
    /// generated partial part with the properties the type does not already have.
    /// </summary>
    /// <remarks>
    /// The counterpart of <see cref="RecordForger"/>, which goes the other way: from an interface to a whole
    /// new type. Here the type exists and stays in charge — every member it declares itself wins.
    /// </remarks>
    [Generator]
    public partial class InterfaceImplementer : IIncrementalGenerator
    {
        const string attributeNamespace = "Subro.RecordForge";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var types = context.ValuesForAttributeWithMetadataName(
                $"{attributeNamespace}.{nameof(ImplementsAttribute)}",
                static (node, _) => node is TypeDeclarationSyntax, //the attribute targets class/struct only
                TransformType);

            context.RegisterSourceOutput(types, Emit);
        }

        static void Emit(SourceProductionContext spc, ImplementInfo info)
            => spc.AddSource(info.HintName, BuildCode(info));

        internal static string BuildCode(ImplementInfo info)
        {
            var sb = new StringBuilder(@"// <auto-generated/>
#nullable enable

");
            int depth = 0;

            bool hasNamespace = info.NameSpace.Length > 0;
            if (hasNamespace)
            {
                sb.Append("namespace ").Append(info.NameSpace).Append("\n{\n");
                depth++;
            }

            foreach (var header in info.ContainingTypeHeaders)
            {
                sb.Indent(depth).Append(header).Append('\n').Indent(depth).Append("{\n");
                depth++;
            }

            sb.Indent(depth).Append(info.TypeHeader);
            for (int i = 0; i < info.InterfacesToDeclare.Length; i++)
                sb.Append(i == 0 ? " : " : ", ").Append(info.InterfacesToDeclare[i]);
            sb.Append('\n').Indent(depth).Append("{\n");
            depth++;

            foreach (var prop in info.Properties)
            {
                //a plain comment rather than <inheritdoc cref="..."/>: the interface name is rendered
                //global::-qualified, which a cref does not accept, and a generic interface would need its
                //own {} escaping on top. Not worth a warning in the consumer's build.
                sb.Indent(depth).Append("// ").Append(prop.DeclaringInterface).Append('.').Append(prop.Name).Append('\n');
                sb.Indent(depth).Append("public ").Append(prop.TypeName).Append(' ').Append(prop.Name)
                    .Append(prop.Setter switch
                    {
                        SetterKind.Set => " { get; set; }",
                        SetterKind.Init => " { get; init; }",
                        _ => " { get; }",
                    })
                    .Append('\n');

                if (!prop.NeedsReadOnlySetterShim) continue;

                //the interface asks for a set accessor the readonly struct cannot have. Rather than refuse,
                //satisfy the interface explicitly and fail at the point someone actually tries to assign
                sb.Indent(depth).Append(prop.TypeName).Append(' ').Append(prop.DeclaringInterface).Append('.')
                    .Append(prop.Name).Append(" { get => this.").Append(prop.Name)
                    .Append("; set => throw new global::System.NotSupportedException(\"This instance is read-only.\"); }\n");
            }

            while (depth > 0)
                sb.Indent(--depth).Append("}\n");

            return sb.ToString();
        }
    }

    internal static class InterfaceImplementerFunctions
    {
        public static StringBuilder Indent(this StringBuilder sb, int depth)
        {
            for (int i = 0; i < depth; i++) sb.Append("    ");
            return sb;
        }
    }
}
