using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text;

namespace Viaduct
{
    /// <summary>
    /// Base class for Viaduct attributes. Has no function of itself.
    /// </summary>
    public abstract class ViaductAttributeBase: Attribute
    {
    }


    /// <summary>    
    /// Can be applied at interface level to set base path
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface)]
    public class BasePathAttribute([StringSyntax(ViaductFunctions.RouteSyntax)] string path) : ViaductAttributeBase
    {
        /// <summary>
        /// Gets the route template path.
        /// </summary>
        [StringSyntax(ViaductFunctions.RouteSyntax)] public string Path { get; } = path;
    }



    /// <summary>    
    /// Can be applied at method level for custom routes. NB, default attributes such as HttpGet, HttpPost, etc. can also be used.
    /// </summary>    
    [AttributeUsage(AttributeTargets.Method)]
    public class CustomRouteAttribute([StringSyntax(ViaductFunctions.RouteSyntax)] string path) : ViaductAttributeBase
    {
        /// <summary>
        /// Gets the route template path.
        /// </summary>
        public string Path { get; } = path;
    }

    /// <summary>
    /// The normal attributes System.Net.Http Attributes such as [HttpGet], [HttpPost] etc. can also be used, but alternatively this attribute can be used in service mappings.
    /// </summary>    
    [AttributeUsage(AttributeTargets.Method)]
    public class HttpMethodTypeAttribute(string Type) : ViaductAttributeBase
    {
        /// <summary>
        /// The http method type (GET/POST/etc)
        /// </summary>
        public string Type { get; } = Type;
    }

    /// <summary>
    /// The one-line summary for this method's endpoint, as it appears in the OpenAPI document and in the
    /// clients generated from it.
    /// </summary>
    /// <remarks>
    /// Only needed when the method has no XML documentation comment, or when the endpoint should read
    /// differently from the method: a <c>&lt;summary&gt;</c> comment is picked up on its own.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Method)]
    public class ViaductSummaryAttribute(string summary) : ViaductAttributeBase
    {
        /// <summary>The summary text.</summary>
        public string Summary { get; } = summary;
    }

    /// <summary>
    /// The longer description for this method's endpoint, shown below the summary in API documentation.
    /// </summary>
    /// <remarks>
    /// As with <see cref="ViaductSummaryAttribute"/>, an XML <c>&lt;remarks&gt;</c> comment is used when this
    /// attribute is absent.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Method)]
    public class ViaductDescriptionAttribute(string description) : ViaductAttributeBase
    {
        /// <summary>The description text.</summary>
        public string Description { get; } = description;
    }

    /// <summary>
    /// The endpoint name for this method, which is also its OpenAPI <c>operationId</c> — the name other code
    /// generators build their method names from.
    /// </summary>
    /// <remarks>
    /// One is generated by default from the interface and method names, e.g. <c>UserService_GetUser</c>. Set
    /// this where that would be wrong, or where it would collide: endpoint names must be unique across the
    /// whole application, not merely within the interface.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Method)]
    public class ViaductEndpointNameAttribute(string name) : ViaductAttributeBase
    {
        /// <summary>The endpoint name.</summary>
        public string Name { get; } = name;
    }

    /// <summary>
    /// Tells the Viaduct generator to ignore this method (for both client and server side)
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public class ViaductIgnoreAttribute : ViaductAttributeBase
    {

    }

    /// <summary>
    /// Tells the Viaduct generator to ignore this method for server endpoint generation
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public class ViaductIgnoreForServerAttribute : ViaductAttributeBase
    {

    }

}
