<Project>
  <PropertyGroup>
    <Version>0.0.1</Version>
    <Authors>Robert Verpalen</Authors>
    <Company>Subro Software</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>aspnetcore;minimal-api;source-generator;dependency-injection;http-client;code-generation</PackageTags>
    <RepositoryUrl>https://github.com/robverp78/Subro.Generators.Nuget</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/robverp78/Subro.Generators.Nuget/tree/main/Viaduct</PackageProjectUrl>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Required for all projects that consume the Viaduct generator -->
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Viaduct.Generated</InterceptorsNamespaces>
  </PropertyGroup>

</Project>
